Parameters:
  AppName:
    Type: String
    Description: Name of the application

Resources:
  CodePipelineServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: 'AWS-CodePipeline-Service'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - 'codepipeline.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: CodePipelinePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'

  Pipeline:
    DependsOn: 
      - MyCodeCommitRepository
      - CodePipelineServiceRole
      - MyArtifactStoreBucket
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Ref AppName
      RoleArn: !GetAtt CodePipelineServiceRole.Arn
      ArtifactStore: 
        Type: S3
        Location: !Ref MyArtifactStoreBucket
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeCommit
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                RepositoryName: !Ref MyCodeCommitRepository
                BranchName: master
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: !Ref AppName
              RunOrder: 1

  MyArtifactStoreBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${AppName}-artifact-store'

  MyCodeCommitRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Ref AppName
      RepositoryDescription: My CodeCommit repository for the ${AppName} application

Outputs:
  PipelineUrl:
    Description: URL of the created CodePipeline
    Value: !Sub "https://console.aws.amazon.com/codesuite/codepipeline/pipelines/${AppName}/view"

  RepositoryUri:
      Description: The URI of the created ECR repository
      Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRRepositoryWallet}"


