Parameters:
  RetentionPeriod:
    Type: Number
    Default: 24
    Description: The number of hours for the data records that are stored in shards to remain accessible. The default value is 24. For more information about the stream retention period

  Shard:
    Type: Number
    Default: 1
    Description: Label ProjectTag

  ENVTag:
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - Prod
      - Test
    Description: Label Enviroment Tag

  VersionTag:
    Type: String
    Default: V.1
    Description: Label Version Tag

  ProjectTag:
    Type: String
    Description: Label ProjectTag

Resources:
  Kinesis:
    Type: AWS::Kinesis::Stream
    Properties:
      Name:
        Ref: AWS::StackName
      RetentionPeriodHours:
        Ref: RetentionPeriod
      ShardCount:
        Ref: Shard
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName
        - Key: ENV
          Value:
            Ref: ENVTag
        - Key: Version
          Value:
            Ref: VersionTag
        - Key: Project
          Value:
            Ref: ProjectTag
