Parameters:
  DelaySeconds:
    Type: Number
    Default: 0
    Description: The time in seconds for which the delivery of all messages in the queue is delayed. You can specify an integer value of 0 to 900 (15 minutes). The default value is 0.

  MaximumMessage:
    Type: Number
    Default: 262144
    Description: specify an integer value from 1,024 bytes (1 KiB) to 262,144 bytes (256 KiB).

  MessageRetention:
    Type: Number
    Default: 345600
    Description: You can specify an integer value from 60 seconds (1 minute) to 1,209,600 seconds (14 days).

  ReceiveMessageWaitTime:
    Type: Number
    Default: 0
    Description: Specifies the duration, in seconds, that the ReceiveMessage action call waits until a message is in the queue in order to include it in the response, rather than returning an empty response if a message isn't yet available. You can specify an integer from 1 to 20. Short polling is used as the default or when you specify 0 for this property.

  VisibilityT:
    Type: Number
    Default: 30
    Description: Values must be from 0 to 43,200 seconds (12 hours). If you don't specify a value, AWS CloudFormation uses the default value of 30 seconds.

  ENVTag:
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - Prod
      - Test
    Description: Label Enviroment Tag

  VersionTag:
    Type: String
    Default: V.1
    Description: Label Version Tag

  ProjectTag:
    Type: String
    Description: Label ProjectTag

Resources:
  SQS:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds:
        Ref: DelaySeconds
      MaximumMessageSize:
        Ref: MaximumMessage
      MessageRetentionPeriod:
        Ref: MessageRetention
      QueueName:
        Ref: AWS::StackName
      ReceiveMessageWaitTimeSeconds:
        Ref: ReceiveMessageWaitTime
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName
        - Key: ENV
          Value:
            Ref: ENVTag
        - Key: Version
          Value:
            Ref: VersionTag
        - Key: Project
          Value:
            Ref: ProjectTag
      VisibilityTimeout:
        Ref: VisibilityT
